@startuml

'botシーケンス図'

participant クライアント1
participant サーバー
participant クライアント2

autonumber
クライアント1 <- サーバー:ゲーム開始通知
クライアント2 <- サーバー:ゲーム開始通知

hnote over クライアント1 : タイマーカウントスタート
hnote over クライアント2 : スタート

クライアント1 -> サーバー:時間送信(60)

クライアント1 <- サーバー:残り60秒
クライアント2 <- サーバー:残り60秒

hnote over クライアント1 : 1:00
hnote over クライアント2 : 1:00

クライアント1 -> サーバー:時間送信(59)

クライアント1 <- サーバー:残り59秒
クライアント2 <- サーバー:残り59秒
hnote over クライアント1 : 0:59
hnote over クライアント2 : 0:59

クライアント1 -> サーバー:時間送信(58)

クライアント1 <- サーバー:残り58秒
クライアント2 <- サーバー:残り58秒
hnote over クライアント1 : 0:58
hnote over クライアント2 : 0:58

クライアント1 -> サーバー:時間送信(0)

クライアント1 <- サーバー:残り0秒
クライアント2 <- サーバー:残り0秒
hnote over クライアント1 : 0:00
hnote over クライアント2 : 0:00

クライアント1 <- サーバー:ゲーム終了
クライアント2 <- サーバー:ゲーム終了

hnote over クライアント1 : 結果表示
hnote over クライアント2 : 結果表示

クライアント1 -> サーバー:退出
クライアント2 -> サーバー:退出
@enduml
