@startuml

'botシーケンス図'

participant プレイヤー1
participant サーバー
participant プレイヤー2

autonumber
プレイヤー1 -> サーバー:プレイヤー１がボールをキャッチ
hnote over サーバー : ボール所有状況を更新\n多重取得チェック

プレイヤー1 <- サーバー:ボールマスターをP1に変更\nボールを破棄
プレイヤー2 <- サーバー:マスター権&ボールを破棄

プレイヤー2 -> サーバー:プレイヤー2がボールをキャッチ
hnote over サーバー : ボール所有状況を更新\n多重取得チェック
プレイヤー2 <- サーバー:ボールマスターをP2に変更\nボールを破棄
プレイヤー1 <- サーバー:マスター権&ボールを破棄

@enduml
