@startuml

'botシーケンス図'

participant プレイヤー1
participant サーバー
participant プレイヤー2

autonumber
プレイヤー1 -> サーバー:プレイヤー１がプレイヤー2の\n投げたボールにヒット
プレイヤー1 <- サーバー:ダウン処理&ライフを減少\nP2のスコアを更新
プレイヤー2 <- サーバー:P1のライフ反映&スコアを加算



@enduml
