@startuml

'botシーケンス図'

participant クライアント1
participant クライアント2
participant クライアント3
participant サーバー

autonumber
hnote over サーバー : 接続受付中

クライアント1 -> サーバー:サーバー接続
hnote over サーバー : ルーム作成
クライアント1 <- サーバー:接続完了通知

クライアント2 -> サーバー:サーバー接続
hnote over サーバー : ルーム参加
クライアント2 <- サーバー:入室完了
クライアント1 <- サーバー:No.2入室通知

クライアント3 -> サーバー:サーバー接続
hnote over サーバー : ルーム参加
クライアント3 <- サーバー:入室完了
クライアント1 <- サーバー:No.3入室通知
クライアント2 <- サーバー:No.3入室通知

@enduml
