@startuml

'botシーケンス図'

participant クライアント1
participant クライアント2
participant クライアント3
participant サーバー

autonumber
hnote over サーバー : ルーム開設中

クライアント1 -> サーバー:ルーム退出
hnote over サーバー : No1退出
クライアント1 <- サーバー:接続解除
クライアント2 <- サーバー:No1退出通知
クライアント3 <- サーバー:No1退出通知

クライアント2 -> サーバー:ルーム退出
hnote over サーバー : No2退出
クライアント2 <- サーバー:接続解除
クライアント3 <- サーバー:No2退出通知


クライアント3 -> サーバー:ルーム退出
hnote over サーバー : No3退出
クライアント3 <- サーバー:接続解除
サーバー -> サーバー:接続数が0になったら
hnote over サーバー : ルーム破棄

@enduml