@startuml

'botシーケンス図'

participant クライアント1
participant クライアント2
participant クライアント3
participant クライアント4
participant サーバー

autonumber
hnote over サーバー : 接続受付中

クライアント1 -> サーバー:マッチング送信
hnote over サーバー : ロビー入室
クライアント1 <- サーバー:ロビー入室通知

クライアント2 -> サーバー:ロビー入室
hnote over サーバー : ルーム参加
クライアント2 <- サーバー:ロビー入室通知

クライアント3 -> サーバー:ロビー入室
hnote over サーバー : ルーム参加
クライアント3 <- サーバー:ロビー入室通知

クライアント4 -> サーバー:ロビー入室
hnote over サーバー : ルーム参加
クライアント4 <- サーバー:マッチング成立通知
クライアント1 <- サーバー:マッチング成立通知
クライアント2 <- サーバー:マッチング成立通知
クライアント3 <- サーバー:マッチング成立通知

クライアント1 -> サーバー:ロビーを退出して指定キー入室
クライアント2 -> サーバー:ロビーを退出して指定キー入室
クライアント3 -> サーバー:ロビーを退出して指定キー入室
クライアント4 -> サーバー:ロビーを退出して指定キー入室

クライアント1 <-> サーバー:各クライアントにゲーム開始通知

@enduml
