@startuml

'botシーケンス図'

participant プレイヤー1
participant サーバー
participant プレイヤー2

autonumber
プレイヤー1 -> サーバー:P1がP2に向けてボールを発射
hnote over サーバー : ボール所持状況更新
プレイヤー1 <- サーバー:ボール生成通知
プレイヤー2 <- サーバー:ボール生成通知

hnote over プレイヤー1 : P1の座標にボールを生成\nプレイヤー2の座標にボール発射
hnote over プレイヤー2 : P1の座標にボールを生成\nボール座標を同期


@enduml
