@startuml

'botシーケンス図'

participant プレイヤー1
participant サーバー
participant プレイヤー2

autonumber
プレイヤー1 -> サーバー:プレイヤー１がプレイヤー2に\n向けて玉1を発射
プレイヤー1 <- サーバー:プレイヤー１の座標から\nプレイヤー2の座標に玉1を発射
プレイヤー2 <- サーバー:プレイヤー１の座標から\nプレイヤー2の座標に玉1を発射

hnote over プレイヤー1 : プレイヤー1の位置を探し\n玉を再生して名前を玉1に設定\nプレイヤー2の座標に玉1を発射
hnote over プレイヤー2 : プレイヤー1の位置を探し\n玉を再生して名前を玉1に設定\nプレイヤー2の座標に玉1を発射

hnote over プレイヤー1 : 玉1がプレイヤー2に被弾(何もしない)
hnote over プレイヤー2 : 玉1がプレイヤー2に被弾
プレイヤー2 -> サーバー:玉1がヒット

プレイヤー1 <- サーバー:玉1がプレイヤー2にヒット
プレイヤー2 <- サーバー:玉1がプレイヤー2にヒット

hnote over プレイヤー1 : プレイヤー2はダウン\n玉1はそのまま転がす
hnote over プレイヤー2 : プレイヤー2はダウン\n玉1はそのまま転がす




プレイヤー2 -> サーバー:プレイヤー2がボールを拾い\nプレイヤー1に向けて玉2を発射
プレイヤー1 <- サーバー:プレイヤー2の座標から\nプレイヤー1の座標に玉2を発射
プレイヤー2 <- サーバー:プレイヤー2の座標から\nプレイヤー1の座標に玉2を発射

hnote over プレイヤー1 : プレイヤー2の位置を探し\n玉を再生して名前を玉2に設定\nプレイヤー1の座標に玉2を発射
hnote over プレイヤー2 : プレイヤー2の位置を探し\n玉を再生して名前を玉2に設定\nプレイヤー1の座標に玉2を発射

hnote over プレイヤー1 : 玉2がプレイヤー1捕球状態で被弾
hnote over プレイヤー2 : 玉2がプレイヤー1捕球状態で被弾(何もしない)

プレイヤー1 -> サーバー:玉2をキャッチ

プレイヤー1 <- サーバー:玉2がプレイヤー1にキャッチ
プレイヤー2 <- サーバー:玉2がプレイヤー2にキャッチ

hnote over プレイヤー1 : プレイヤー1が玉所持状態\n玉2を破棄
hnote over プレイヤー2 : プレイヤー1が玉所持状態\n玉2を破棄


@enduml
